### ISSUE TITLE
~~

### ISSUE THREAD

**Issue by sunshin15** [Xflick/NumGuess#1]
I think this might not be a good choice.(follows)
do
{
    ......
}  while (num[0] == num[1] || num[1] == num[2] || num[2] == num[0]);

Especially when we need to create more numbers which do not repeat....
I have an idea:

for (int i=0;i<=2;i++)
{
	x=rand()%10;
	while (ranNum[x]==1)	//make sure that the numbers won't repeat
		x=rand()%10;
	ranNum[x]=1;	
	a[i]=x;
}

This will cost less time~~

**Comment by Xflick** [comment]
OK. That's quite a good choice, But actually I think the best idea is to create a list (not an array), choose an entry of the list at random, then delete it from the list. But because the teacher have not mentioned the list class yet, I choose this method. Thank you for your advice~

**Comment by weninsjtu** [comment]
You have considered many unexpected cases.However,when i enter "5 4 1" the warning appears and "541" is ok, which is a small mistake I think

**Comment by Xflick** [comment]
That entering "5 4 1" is invalid is actually what I want the program to do. In my own opinion, "5 4 1" is not a valid integer.
